name: Cypress tests
on: push
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Open Web Client Directory
        working-directory: src/webclient
        run: |
          ls

      - name: Cypress run
        uses: cypress-io/github-action@v6.6.0
        with:
          path: ./
          spec: cypress/e2e/**.cy.js
          if-no-files-found: error
          browser: chrome
          build: npm run build
          start: npm start
          wait-on: "http://localhost:4200"
